// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GuideRibbonLine.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace pb {

namespace {

const ::google::protobuf::Descriptor* GuideRibbonLine_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GuideRibbonLine_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_GuideRibbonLine_2eproto() {
  protobuf_AddDesc_GuideRibbonLine_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "GuideRibbonLine.proto");
  GOOGLE_CHECK(file != NULL);
  GuideRibbonLine_descriptor_ = file->message_type(0);
  static const int GuideRibbonLine_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GuideRibbonLine, points_),
  };
  GuideRibbonLine_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GuideRibbonLine_descriptor_,
      GuideRibbonLine::default_instance_,
      GuideRibbonLine_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GuideRibbonLine, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GuideRibbonLine, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(GuideRibbonLine));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_GuideRibbonLine_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GuideRibbonLine_descriptor_, &GuideRibbonLine::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_GuideRibbonLine_2eproto() {
  delete GuideRibbonLine::default_instance_;
  delete GuideRibbonLine_reflection_;
}

void protobuf_AddDesc_GuideRibbonLine_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::pb::protobuf_AddDesc_bootes_2fdances_2fproto_2fStage_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025GuideRibbonLine.proto\022\002pb\032\037bootes/danc"
    "es/proto/Stage.proto\",\n\017GuideRibbonLine\022"
    "\031\n\006points\030\001 \003(\0132\t.pb.Point", 106);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GuideRibbonLine.proto", &protobuf_RegisterTypes);
  GuideRibbonLine::default_instance_ = new GuideRibbonLine();
  GuideRibbonLine::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_GuideRibbonLine_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_GuideRibbonLine_2eproto {
  StaticDescriptorInitializer_GuideRibbonLine_2eproto() {
    protobuf_AddDesc_GuideRibbonLine_2eproto();
  }
} static_descriptor_initializer_GuideRibbonLine_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int GuideRibbonLine::kPointsFieldNumber;
#endif  // !_MSC_VER

GuideRibbonLine::GuideRibbonLine()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void GuideRibbonLine::InitAsDefaultInstance() {
}

GuideRibbonLine::GuideRibbonLine(const GuideRibbonLine& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void GuideRibbonLine::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GuideRibbonLine::~GuideRibbonLine() {
  SharedDtor();
}

void GuideRibbonLine::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GuideRibbonLine::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GuideRibbonLine::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GuideRibbonLine_descriptor_;
}

const GuideRibbonLine& GuideRibbonLine::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_GuideRibbonLine_2eproto();  return *default_instance_;
}

GuideRibbonLine* GuideRibbonLine::default_instance_ = NULL;

GuideRibbonLine* GuideRibbonLine::New() const {
  return new GuideRibbonLine;
}

void GuideRibbonLine::Clear() {
  points_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool GuideRibbonLine::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .pb.Point points = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_points:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_points()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_points;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void GuideRibbonLine::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .pb.Point points = 1;
  for (int i = 0; i < this->points_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->points(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* GuideRibbonLine::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .pb.Point points = 1;
  for (int i = 0; i < this->points_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->points(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int GuideRibbonLine::ByteSize() const {
  int total_size = 0;
  
  // repeated .pb.Point points = 1;
  total_size += 1 * this->points_size();
  for (int i = 0; i < this->points_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->points(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GuideRibbonLine::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const GuideRibbonLine* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const GuideRibbonLine*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GuideRibbonLine::MergeFrom(const GuideRibbonLine& from) {
  GOOGLE_CHECK_NE(&from, this);
  points_.MergeFrom(from.points_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void GuideRibbonLine::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GuideRibbonLine::CopyFrom(const GuideRibbonLine& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GuideRibbonLine::IsInitialized() const {
  
  for (int i = 0; i < points_size(); i++) {
    if (!this->points(i).IsInitialized()) return false;
  }
  return true;
}

void GuideRibbonLine::Swap(GuideRibbonLine* other) {
  if (other != this) {
    points_.Swap(&other->points_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata GuideRibbonLine::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GuideRibbonLine_descriptor_;
  metadata.reflection = GuideRibbonLine_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)
