// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GuideRibbonSpline.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace pb {

namespace {

const ::google::protobuf::Descriptor* GuideRibbonSpline_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GuideRibbonSpline_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_GuideRibbonSpline_2eproto() {
  protobuf_AddDesc_GuideRibbonSpline_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "GuideRibbonSpline.proto");
  GOOGLE_CHECK(file != NULL);
  GuideRibbonSpline_descriptor_ = file->message_type(0);
  static const int GuideRibbonSpline_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GuideRibbonSpline, points_),
  };
  GuideRibbonSpline_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GuideRibbonSpline_descriptor_,
      GuideRibbonSpline::default_instance_,
      GuideRibbonSpline_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GuideRibbonSpline, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GuideRibbonSpline, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(GuideRibbonSpline));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_GuideRibbonSpline_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GuideRibbonSpline_descriptor_, &GuideRibbonSpline::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_GuideRibbonSpline_2eproto() {
  delete GuideRibbonSpline::default_instance_;
  delete GuideRibbonSpline_reflection_;
}

void protobuf_AddDesc_GuideRibbonSpline_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::pb::protobuf_AddDesc_bootes_2fdances_2fproto_2fStage_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027GuideRibbonSpline.proto\022\002pb\032\037bootes/da"
    "nces/proto/Stage.proto\".\n\021GuideRibbonSpl"
    "ine\022\031\n\006points\030\001 \003(\0132\t.pb.Point", 110);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GuideRibbonSpline.proto", &protobuf_RegisterTypes);
  GuideRibbonSpline::default_instance_ = new GuideRibbonSpline();
  GuideRibbonSpline::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_GuideRibbonSpline_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_GuideRibbonSpline_2eproto {
  StaticDescriptorInitializer_GuideRibbonSpline_2eproto() {
    protobuf_AddDesc_GuideRibbonSpline_2eproto();
  }
} static_descriptor_initializer_GuideRibbonSpline_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int GuideRibbonSpline::kPointsFieldNumber;
#endif  // !_MSC_VER

GuideRibbonSpline::GuideRibbonSpline()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void GuideRibbonSpline::InitAsDefaultInstance() {
}

GuideRibbonSpline::GuideRibbonSpline(const GuideRibbonSpline& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void GuideRibbonSpline::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GuideRibbonSpline::~GuideRibbonSpline() {
  SharedDtor();
}

void GuideRibbonSpline::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GuideRibbonSpline::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GuideRibbonSpline::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GuideRibbonSpline_descriptor_;
}

const GuideRibbonSpline& GuideRibbonSpline::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_GuideRibbonSpline_2eproto();  return *default_instance_;
}

GuideRibbonSpline* GuideRibbonSpline::default_instance_ = NULL;

GuideRibbonSpline* GuideRibbonSpline::New() const {
  return new GuideRibbonSpline;
}

void GuideRibbonSpline::Clear() {
  points_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool GuideRibbonSpline::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .pb.Point points = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_points:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_points()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_points;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void GuideRibbonSpline::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .pb.Point points = 1;
  for (int i = 0; i < this->points_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->points(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* GuideRibbonSpline::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .pb.Point points = 1;
  for (int i = 0; i < this->points_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->points(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int GuideRibbonSpline::ByteSize() const {
  int total_size = 0;
  
  // repeated .pb.Point points = 1;
  total_size += 1 * this->points_size();
  for (int i = 0; i < this->points_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->points(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GuideRibbonSpline::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const GuideRibbonSpline* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const GuideRibbonSpline*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GuideRibbonSpline::MergeFrom(const GuideRibbonSpline& from) {
  GOOGLE_CHECK_NE(&from, this);
  points_.MergeFrom(from.points_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void GuideRibbonSpline::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GuideRibbonSpline::CopyFrom(const GuideRibbonSpline& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GuideRibbonSpline::IsInitialized() const {
  
  for (int i = 0; i < points_size(); i++) {
    if (!this->points(i).IsInitialized()) return false;
  }
  return true;
}

void GuideRibbonSpline::Swap(GuideRibbonSpline* other) {
  if (other != this) {
    points_.Swap(&other->points_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata GuideRibbonSpline::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GuideRibbonSpline_descriptor_;
  metadata.reflection = GuideRibbonSpline_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)
