// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MotionWiimoteSimple.proto

#ifndef PROTOBUF_MotionWiimoteSimple_2eproto__INCLUDED
#define PROTOBUF_MotionWiimoteSimple_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "bootes/dances/proto/Stage.pb.h"
// @@protoc_insertion_point(includes)

namespace pb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MotionWiimoteSimple_2eproto();
void protobuf_AssignDesc_MotionWiimoteSimple_2eproto();
void protobuf_ShutdownFile_MotionWiimoteSimple_2eproto();

class MotionWiimoteSimple;
class MotionWiimoteSimple_Entry;

// ===================================================================

class MotionWiimoteSimple_Entry : public ::google::protobuf::Message {
 public:
  MotionWiimoteSimple_Entry();
  virtual ~MotionWiimoteSimple_Entry();
  
  MotionWiimoteSimple_Entry(const MotionWiimoteSimple_Entry& from);
  
  inline MotionWiimoteSimple_Entry& operator=(const MotionWiimoteSimple_Entry& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MotionWiimoteSimple_Entry& default_instance();
  
  void Swap(MotionWiimoteSimple_Entry* other);
  
  // implements Message ----------------------------------------------
  
  MotionWiimoteSimple_Entry* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MotionWiimoteSimple_Entry& from);
  void MergeFrom(const MotionWiimoteSimple_Entry& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 t = 1;
  inline bool has_t() const;
  inline void clear_t();
  static const int kTFieldNumber = 1;
  inline ::google::protobuf::int32 t() const;
  inline void set_t(::google::protobuf::int32 value);
  
  // required .pb.Motion.Accel accel = 2;
  inline bool has_accel() const;
  inline void clear_accel();
  static const int kAccelFieldNumber = 2;
  inline const ::pb::Motion_Accel& accel() const;
  inline ::pb::Motion_Accel* mutable_accel();
  inline ::pb::Motion_Accel* release_accel();
  
  // required .pb.Motion.Gyro gyro = 3;
  inline bool has_gyro() const;
  inline void clear_gyro();
  static const int kGyroFieldNumber = 3;
  inline const ::pb::Motion_Gyro& gyro() const;
  inline ::pb::Motion_Gyro* mutable_gyro();
  inline ::pb::Motion_Gyro* release_gyro();
  
  // required .pb.Motion.Gyro orien = 4;
  inline bool has_orien() const;
  inline void clear_orien();
  static const int kOrienFieldNumber = 4;
  inline const ::pb::Motion_Gyro& orien() const;
  inline ::pb::Motion_Gyro* mutable_orien();
  inline ::pb::Motion_Gyro* release_orien();
  
  // @@protoc_insertion_point(class_scope:pb.MotionWiimoteSimple.Entry)
 private:
  inline void set_has_t();
  inline void clear_has_t();
  inline void set_has_accel();
  inline void clear_has_accel();
  inline void set_has_gyro();
  inline void clear_has_gyro();
  inline void set_has_orien();
  inline void clear_has_orien();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::pb::Motion_Accel* accel_;
  ::pb::Motion_Gyro* gyro_;
  ::pb::Motion_Gyro* orien_;
  ::google::protobuf::int32 t_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_MotionWiimoteSimple_2eproto();
  friend void protobuf_AssignDesc_MotionWiimoteSimple_2eproto();
  friend void protobuf_ShutdownFile_MotionWiimoteSimple_2eproto();
  
  void InitAsDefaultInstance();
  static MotionWiimoteSimple_Entry* default_instance_;
};
// -------------------------------------------------------------------

class MotionWiimoteSimple : public ::google::protobuf::Message {
 public:
  MotionWiimoteSimple();
  virtual ~MotionWiimoteSimple();
  
  MotionWiimoteSimple(const MotionWiimoteSimple& from);
  
  inline MotionWiimoteSimple& operator=(const MotionWiimoteSimple& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MotionWiimoteSimple& default_instance();
  
  void Swap(MotionWiimoteSimple* other);
  
  // implements Message ----------------------------------------------
  
  MotionWiimoteSimple* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MotionWiimoteSimple& from);
  void MergeFrom(const MotionWiimoteSimple& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef MotionWiimoteSimple_Entry Entry;
  
  // accessors -------------------------------------------------------
  
  // required int32 stept = 1;
  inline bool has_stept() const;
  inline void clear_stept();
  static const int kSteptFieldNumber = 1;
  inline ::google::protobuf::int32 stept() const;
  inline void set_stept(::google::protobuf::int32 value);
  
  // repeated .pb.MotionWiimoteSimple.Entry minseq = 2;
  inline int minseq_size() const;
  inline void clear_minseq();
  static const int kMinseqFieldNumber = 2;
  inline const ::pb::MotionWiimoteSimple_Entry& minseq(int index) const;
  inline ::pb::MotionWiimoteSimple_Entry* mutable_minseq(int index);
  inline ::pb::MotionWiimoteSimple_Entry* add_minseq();
  inline const ::google::protobuf::RepeatedPtrField< ::pb::MotionWiimoteSimple_Entry >&
      minseq() const;
  inline ::google::protobuf::RepeatedPtrField< ::pb::MotionWiimoteSimple_Entry >*
      mutable_minseq();
  
  // repeated .pb.MotionWiimoteSimple.Entry maxseq = 3;
  inline int maxseq_size() const;
  inline void clear_maxseq();
  static const int kMaxseqFieldNumber = 3;
  inline const ::pb::MotionWiimoteSimple_Entry& maxseq(int index) const;
  inline ::pb::MotionWiimoteSimple_Entry* mutable_maxseq(int index);
  inline ::pb::MotionWiimoteSimple_Entry* add_maxseq();
  inline const ::google::protobuf::RepeatedPtrField< ::pb::MotionWiimoteSimple_Entry >&
      maxseq() const;
  inline ::google::protobuf::RepeatedPtrField< ::pb::MotionWiimoteSimple_Entry >*
      mutable_maxseq();
  
  // @@protoc_insertion_point(class_scope:pb.MotionWiimoteSimple)
 private:
  inline void set_has_stept();
  inline void clear_has_stept();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::pb::MotionWiimoteSimple_Entry > minseq_;
  ::google::protobuf::RepeatedPtrField< ::pb::MotionWiimoteSimple_Entry > maxseq_;
  ::google::protobuf::int32 stept_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_MotionWiimoteSimple_2eproto();
  friend void protobuf_AssignDesc_MotionWiimoteSimple_2eproto();
  friend void protobuf_ShutdownFile_MotionWiimoteSimple_2eproto();
  
  void InitAsDefaultInstance();
  static MotionWiimoteSimple* default_instance_;
};
// ===================================================================


// ===================================================================

// MotionWiimoteSimple_Entry

// required int32 t = 1;
inline bool MotionWiimoteSimple_Entry::has_t() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MotionWiimoteSimple_Entry::set_has_t() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MotionWiimoteSimple_Entry::clear_has_t() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MotionWiimoteSimple_Entry::clear_t() {
  t_ = 0;
  clear_has_t();
}
inline ::google::protobuf::int32 MotionWiimoteSimple_Entry::t() const {
  return t_;
}
inline void MotionWiimoteSimple_Entry::set_t(::google::protobuf::int32 value) {
  set_has_t();
  t_ = value;
}

// required .pb.Motion.Accel accel = 2;
inline bool MotionWiimoteSimple_Entry::has_accel() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MotionWiimoteSimple_Entry::set_has_accel() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MotionWiimoteSimple_Entry::clear_has_accel() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MotionWiimoteSimple_Entry::clear_accel() {
  if (accel_ != NULL) accel_->::pb::Motion_Accel::Clear();
  clear_has_accel();
}
inline const ::pb::Motion_Accel& MotionWiimoteSimple_Entry::accel() const {
  return accel_ != NULL ? *accel_ : *default_instance_->accel_;
}
inline ::pb::Motion_Accel* MotionWiimoteSimple_Entry::mutable_accel() {
  set_has_accel();
  if (accel_ == NULL) accel_ = new ::pb::Motion_Accel;
  return accel_;
}
inline ::pb::Motion_Accel* MotionWiimoteSimple_Entry::release_accel() {
  clear_has_accel();
  ::pb::Motion_Accel* temp = accel_;
  accel_ = NULL;
  return temp;
}

// required .pb.Motion.Gyro gyro = 3;
inline bool MotionWiimoteSimple_Entry::has_gyro() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MotionWiimoteSimple_Entry::set_has_gyro() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MotionWiimoteSimple_Entry::clear_has_gyro() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MotionWiimoteSimple_Entry::clear_gyro() {
  if (gyro_ != NULL) gyro_->::pb::Motion_Gyro::Clear();
  clear_has_gyro();
}
inline const ::pb::Motion_Gyro& MotionWiimoteSimple_Entry::gyro() const {
  return gyro_ != NULL ? *gyro_ : *default_instance_->gyro_;
}
inline ::pb::Motion_Gyro* MotionWiimoteSimple_Entry::mutable_gyro() {
  set_has_gyro();
  if (gyro_ == NULL) gyro_ = new ::pb::Motion_Gyro;
  return gyro_;
}
inline ::pb::Motion_Gyro* MotionWiimoteSimple_Entry::release_gyro() {
  clear_has_gyro();
  ::pb::Motion_Gyro* temp = gyro_;
  gyro_ = NULL;
  return temp;
}

// required .pb.Motion.Gyro orien = 4;
inline bool MotionWiimoteSimple_Entry::has_orien() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MotionWiimoteSimple_Entry::set_has_orien() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MotionWiimoteSimple_Entry::clear_has_orien() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MotionWiimoteSimple_Entry::clear_orien() {
  if (orien_ != NULL) orien_->::pb::Motion_Gyro::Clear();
  clear_has_orien();
}
inline const ::pb::Motion_Gyro& MotionWiimoteSimple_Entry::orien() const {
  return orien_ != NULL ? *orien_ : *default_instance_->orien_;
}
inline ::pb::Motion_Gyro* MotionWiimoteSimple_Entry::mutable_orien() {
  set_has_orien();
  if (orien_ == NULL) orien_ = new ::pb::Motion_Gyro;
  return orien_;
}
inline ::pb::Motion_Gyro* MotionWiimoteSimple_Entry::release_orien() {
  clear_has_orien();
  ::pb::Motion_Gyro* temp = orien_;
  orien_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// MotionWiimoteSimple

// required int32 stept = 1;
inline bool MotionWiimoteSimple::has_stept() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MotionWiimoteSimple::set_has_stept() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MotionWiimoteSimple::clear_has_stept() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MotionWiimoteSimple::clear_stept() {
  stept_ = 0;
  clear_has_stept();
}
inline ::google::protobuf::int32 MotionWiimoteSimple::stept() const {
  return stept_;
}
inline void MotionWiimoteSimple::set_stept(::google::protobuf::int32 value) {
  set_has_stept();
  stept_ = value;
}

// repeated .pb.MotionWiimoteSimple.Entry minseq = 2;
inline int MotionWiimoteSimple::minseq_size() const {
  return minseq_.size();
}
inline void MotionWiimoteSimple::clear_minseq() {
  minseq_.Clear();
}
inline const ::pb::MotionWiimoteSimple_Entry& MotionWiimoteSimple::minseq(int index) const {
  return minseq_.Get(index);
}
inline ::pb::MotionWiimoteSimple_Entry* MotionWiimoteSimple::mutable_minseq(int index) {
  return minseq_.Mutable(index);
}
inline ::pb::MotionWiimoteSimple_Entry* MotionWiimoteSimple::add_minseq() {
  return minseq_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pb::MotionWiimoteSimple_Entry >&
MotionWiimoteSimple::minseq() const {
  return minseq_;
}
inline ::google::protobuf::RepeatedPtrField< ::pb::MotionWiimoteSimple_Entry >*
MotionWiimoteSimple::mutable_minseq() {
  return &minseq_;
}

// repeated .pb.MotionWiimoteSimple.Entry maxseq = 3;
inline int MotionWiimoteSimple::maxseq_size() const {
  return maxseq_.size();
}
inline void MotionWiimoteSimple::clear_maxseq() {
  maxseq_.Clear();
}
inline const ::pb::MotionWiimoteSimple_Entry& MotionWiimoteSimple::maxseq(int index) const {
  return maxseq_.Get(index);
}
inline ::pb::MotionWiimoteSimple_Entry* MotionWiimoteSimple::mutable_maxseq(int index) {
  return maxseq_.Mutable(index);
}
inline ::pb::MotionWiimoteSimple_Entry* MotionWiimoteSimple::add_maxseq() {
  return maxseq_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pb::MotionWiimoteSimple_Entry >&
MotionWiimoteSimple::maxseq() const {
  return maxseq_;
}
inline ::google::protobuf::RepeatedPtrField< ::pb::MotionWiimoteSimple_Entry >*
MotionWiimoteSimple::mutable_maxseq() {
  return &maxseq_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MotionWiimoteSimple_2eproto__INCLUDED
